version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "5173:5173"
    volumes:
    - ./frontend/public/:/app/public
    - ./frontend/src/:/app/src:ro
    environment:
    - NODE_ENV=${NODE_ENV:-development}
